image: bjodah/chemreac  # git, g++, lapack, cython, py.test etc.
git:
    path: github.com/chemreac/block_diag_ilu
script:
  - cd tests
  - make
  - make clean
  - make DEFINES=-DWITH_BLOCK_DIAG_ILU_DGETRF
  - cd ../python_prototype
  - export PATH=$MINICONDA_PATH/bin:$PATH  # Cython present in miniconda installation
  - PYTHONPATH=. py.test
  - export NP_INC=$(python -c "import numpy; print(numpy.get_include())")
  - echo $NP_INC
  - python setup.py build_ext -i
  - PYTHONPATH=. USE_FAST_FAKELU=1 py.test
  - PYTHONPATH=. python demo.py
  - rm _block_diag_ilu.so
  - WITH_BLOCK_DIAG_ILU_DGETRF=1 python setup.py build_ext -i
  - PYTHONPATH=. USE_FAST_FAKELU=1 py.test
  - PYTHONPATH=. python demo.py
  - rm _block_diag_ilu.so
  - WITH_BLOCK_DIAG_ILU_OPENMP=1 WITH_BLOCK_DIAG_ILU_DGETRF=0 python setup.py build_ext -i
  - PYTHONPATH=. USE_FAST_FAKELU=1 py.test
  - PYTHONPATH=. python demo.py
  - rm _block_diag_ilu.so
  - WITH_BLOCK_DIAG_ILU_OPENMP=1 WITH_BLOCK_DIAG_ILU_DGETRF=1 python setup.py build_ext -i
  - PYTHONPATH=. USE_FAST_FAKELU=1 py.test
  - PYTHONPATH=. python demo.py
