image: bjodah/chemreac  # git, g++, lapack, cython, py.test etc.
git:
    path: github.com/bjodah/block_diag_ilu
script:
  - cd tests
  - make
  - cd ../python_prototype
  - PYTHONPATH=. py.test
  - export PATH=$MINICONDA_PATH/bin:$PATH  # Cython present in miniconda installation
  - CPLUS_INCLUDE_PATH=../include python setup.py build_ext -i
  - PYTHONPATH=. USE_FAST_FAKELU=1 py.test
