build:
  image: bjodah/bjodahimg16dev:latest
  environment:
    - CPLUS_INCLUDE_PATH=/opt/boost_1_63_0/include
    - LIBRARY_PATH=/opt/boost_1_63_0/lib
    - LD_LIBRARY_PATH=/opt/boost_1_63_0/lib
  commands:
    - ./scripts/ci.sh block_diag_ilu
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: block_diag_ilu
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
    when:
      branch: master
