package:
    name: block_diag_ilu
    version: 0.3.0.git

source:
    path: ../

# You may want to exchange openblas with e.g. lapack
build:
  string: np{{np}}py{{py}}_o0
  features:
    - openblas

requirements:
  build:
    - python
    - numpy
    - cython
    - openblas
  run:
    - python
    - numpy
    - openblas


test:
  requires:
    - python
    - pytest

  imports:
    - block_diag_ilu

about:
  home: https://github.com/chemreac/block_diag_ilu
  license: Simplified BSD license
