{% set name = "block_diag_ilu" %}
{% set version = "0.4.0.dev0+git" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 200
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20*  # [not win]
    - clangdev >=6.0
    - libcxx >=6.0
    - python
    - setuptools
    - pip
    - cython
    - numpy
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20*  # [not win]
    - libcxx >=6.0
    - python
    - numpy

test:
  requires:
    - pytest
    - scipy
  imports:
    - block_diag_ilu

about:
  home: https://github.com/chemreac/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Incomplete LU factorization of block diagonal matrices with weak sub-/super-diagonals.'


extra:
  recipe-maintainers:
    - bjodah
