package:
    name: block_diag_ilu
    version: 0.3.0.git

source:
    path: ../

build:
  number: 2

requirements:
  build:
    - python
    - numpy
    - cython
    - lapack
  run:
    - python
    - numpy
    - lapack


test:
  requires:
    - python
    - pytest

  imports:
    - block_diag_ilu

about:
  home: https://github.com/chemreac/block_diag_ilu
  license: Simplified BSD license
